user_name=input("Kullanıcı adınızı giriniz: ")
user_msg="hoşgeldin {},bugün nasılsınız?".format(user_name)
print(user_msg)
user_age=int(input("Yaşınızı giriniz: "))
user_msg2="yaşınız {} ve 10 yıl sonra {} yaşında olacaksınız.".format(user_age,user_age+10)
print(user_msg2)
user_nattion=input("Uyruğunuzu giriniz: ")
user_msg3=f"uyruğunuz {user_nattion}  vatandaşıdır."
print(user_msg3)
user_maas=float(input("Maaş beklentiniz: "))
user_msg4="Maaş beklentiniz {0:8.2f}".format(user_maas)
print(user_msg4)
user_msg5="Hoşgeldin "+user_name+" yaşınız "+str(user_age)+" uyruğunuz "+user_nattion+" maaş beklentiniz "+str(user_maas)
print(user_msg5)